name: mine_clicker
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  provider: ^6.0.5
  audioplayers: ^0.20.1
  shared_preferences: ^2.0.17
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_native_splash: ^2.2.17

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/others/pickaxe.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/blocks/
    - assets/images/items/
    - assets/images/tools/
    - assets/images/destroy_effect/
    - assets/images/others/